#!/bin/sh
#PBS -N {experiment_name}
#PBS -q gpu_1
#PBS -P CSCI1166
#PBS -l select=1:ncpus=8:mpiprocs=8:mem=16gb:ngpus=1
#PBS -l walltime=2:00:00
#PBS -o /mnt/lustre/users/iferreira/distillation-decomposition/experiments/{experiment_name}/logs
#PBS -e /mnt/lustre/users/iferreira/distillation-decomposition/experiments/{experiment_name}/errors
#PBS -m abe -M u25755422@tuks.co.za

ulimit -s unlimited

module load chpc/python/anaconda/3-2024.10.1
source /home/iferreira/myenv/bin/activate

date
echo -e 'Running {python_cmd}\n'

start_time=$(date +%s)

cd /mnt/lustre/users/iferreira/distillation-decomposition
{python_cmd}

echo -e "\nTotal execution time: $(( $(date +%s) - start_time)) seconds"